name: PR Workflow

permissions:
  pull-requests: write
  actions: write

on:
  pull_request:
    types: [opened, closed]

jobs:
  on_open:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache zcli binary
        id: cache-zcli
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/zcli
          key: zcli-linux-amd64-$(date +%Y%m%d)
          restore-keys: zcli-linux-amd64

      - name: Install zcli
        if: steps.cache-zcli.outputs.cache-hit != 'true'
        run: |
          BINARY="zcli-linux-amd64"
          echo "Downloading $BINARY..."
          wget -q https://github.com/zeropsio/zcli/releases/latest/download/$BINARY -O /usr/local/bin/zcli
          chmod +x /usr/local/bin/zcli
          echo "zcli installed successfully."

      - name: Verify zcli installation
        run: zcli version

      - name: Post comment on PR open
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = require('@actions/github').context;
            const github = require('@actions/github');
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: 'A pull request has been opened.'
            });

  on_close:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache zcli binary
        id: cache-zcli
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/zcli
          key: zcli-linux-amd64-$(date +%Y%m%d)
          restore-keys: zcli-linux-amd64

      - name: Install zcli
        if: steps.cache-zcli.outputs.cache-hit != 'true'
        run: |
          BINARY="zcli-linux-amd64"
          echo "Downloading $BINARY..."
          wget -q https://github.com/zeropsio/zcli/releases/latest/download/$BINARY -O /usr/local/bin/zcli
          chmod +x /usr/local/bin/zcli
          echo "zcli installed successfully."

      - name: Verify zcli installation
        run: zcli version

      - name: Post comment on PR close
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = require('@actions/github').context;
            const github = require('@actions/github');
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: 'A pull request has been closed.'
            });
